
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SYMBOL SYMBOL_COUNTspecies_list : species_list speciesspecies_list : speciesspecies : SYMBOLspecies : SYMBOL SYMBOL_COUNT'
    
_lr_action_items = {'SYMBOL':([0,1,2,3,4,5,],[3,3,-2,-3,-1,-4,]),'$end':([1,2,3,4,5,],[0,-2,-3,-1,-4,]),'SYMBOL_COUNT':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'species_list':([0,],[1,]),'species':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> species_list","S'",1,None,None,None),
  ('species_list -> species_list species','species_list',2,'p_op1','ExpYacc.py',7),
  ('species_list -> species','species_list',1,'p_op2','ExpYacc.py',12),
  ('species -> SYMBOL','species',1,'p_op3','ExpYacc.py',17),
  ('species -> SYMBOL SYMBOL_COUNT','species',2,'p_op4','ExpYacc.py',22),
]
